// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPbYANRXERqEnR0QLiL5cfDo_2EfqVK10',
    appId: '1:383632263981:web:5a71a8b8c23db4a08021a4',
    messagingSenderId: '383632263981',
    projectId: 'react-app-8ea4d',
    authDomain: 'react-app-8ea4d.firebaseapp.com',
    databaseURL: 'https://react-app-8ea4d-default-rtdb.firebaseio.com',
    storageBucket: 'react-app-8ea4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfwFu_pNtPwLsyTSbV-iJGpqKx58ZCwg',
    appId: '1:383632263981:android:1ad91e58a1501aeb8021a4',
    messagingSenderId: '383632263981',
    projectId: 'react-app-8ea4d',
    databaseURL: 'https://react-app-8ea4d-default-rtdb.firebaseio.com',
    storageBucket: 'react-app-8ea4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFvnzdqQhMftICyiZ6xXP6HQ8WdFx9JvY',
    appId: '1:383632263981:ios:cd65b7b40617aed28021a4',
    messagingSenderId: '383632263981',
    projectId: 'react-app-8ea4d',
    databaseURL: 'https://react-app-8ea4d-default-rtdb.firebaseio.com',
    storageBucket: 'react-app-8ea4d.firebasestorage.app',
    androidClientId: '383632263981-mlal7ik3dh0td820hs1ka9iavusqb46i.apps.googleusercontent.com',
    iosClientId: '383632263981-fondm4sp7sk07em9b8b4knrs444qrj04.apps.googleusercontent.com',
    iosBundleId: 'com.app.primeTravelFlutterUiKit',
  );

}